{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM users;" }
   ]
  },
  {
   "title": "Active Portfolios",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM portfolios WHERE is_active IS TRUE;"
    }
   ]
  },
  {
   "title": "Average rebalance time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_metrics_service_command_execution_duration_seconds_sum{command=\"rebalance_simple\"}[$__rate_interval]) / rate(prometheus_metrics_service_command_execution_duration_seconds_count{command=\"rebalance_simple\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rebalance Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM rebalance_logs;"
    }
   ]
  },
  {
   "title": "Command Timeouts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_metrics_service_command_timeouts_total{command=\"rebalance_simple\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Portfolios Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "increase(prometheus_metrics_service_portfolios_processed_total{command=\"rebalance_simple\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pairs",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 39, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH paired_tokens AS (\n  SELECT\n    t1.token_symbol AS token_x,\n    t2.token_symbol AS token_y,\n    1 AS paired\n  FROM\n    public.portfolio_assets AS t1\n    JOIN public.portfolio_assets AS t2 ON t1.portfolio_id = t2.portfolio_id\n    AND t1.id < t2.id\n  WHERE\n    t1.portfolio_id IN (\n      SELECT portfolio_id\n      FROM public.portfolio_assets\n      GROUP BY portfolio_id\n      HAVING COUNT(*) = 2\n    )\n),\nall_tokens AS (\n  SELECT DISTINCT token_symbol FROM public.portfolio_assets\n),\nall_pairs AS (\n  SELECT \n    a.token_symbol AS token_x,\n    b.token_symbol AS token_y,\n    0 AS paired\n  FROM all_tokens a\n  CROSS JOIN all_tokens b\n  WHERE a.token_symbol < b.token_symbol\n)\nSELECT \n  token_x,\n  token_y,\n  MAX(paired) AS paired\nFROM (\n  SELECT * FROM paired_tokens\n  UNION ALL\n  SELECT * FROM all_pairs\n) combined\nGROUP BY token_x, token_y\n"
    }
   ]
  }
 ]
}