{
 "title": "Portfolio Performance & Rebalancing Overview",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "portfolio",
    "query": "SELECT name as __text, id as __value FROM portfolios"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "SELECT count(*) FROM users;" }
   ]
  },
  {
   "title": "Active Portfolios",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM portfolios WHERE is_active = true;"
    }
   ]
  },
  {
   "title": "Total Value (at last rebalance)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(rl.value_after_usd) FROM rebalance_logs rl INNER JOIN ( SELECT portfolio_id, max(executed_at) as max_executed_at FROM rebalance_logs GROUP BY portfolio_id ) as latest_logs ON rl.portfolio_id = latest_logs.portfolio_id AND rl.executed_at = latest_logs.max_executed_at;"
    }
   ]
  },
  {
   "title": "Total Rebalance Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM rebalance_logs;"
    }
   ]
  },
  {
   "title": "Portfolio Value for: $portfolio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  executed_at AS \"time\",\n  sum(value_after_usd) AS \"Total Value\"\nFROM rebalance_logs\nWHERE\n  portfolio_id = ${portfolio:raw} AND\n  $__timeFilter(executed_at)\nGROUP BY executed_at\nORDER BY executed_at;"
    }
   ]
  },
  {
   "title": "Target Asset Allocation",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  token_symbol,\n  target_allocation_percent\nFROM portfolio_assets\nWHERE portfolio_id = ${portfolio:raw};"
    }
   ]
  },
  {
   "title": "Last Rebalance Log",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  executed_at,\n  token_symbol,\n  quantity_delta,\n  current_allocation_percent AS \"Allocation Before\",\n  target_allocation_percent AS \"Allocation After\",\n  price_usd\nFROM rebalance_logs\nWHERE portfolio_id = ${portfolio:raw}\nORDER BY executed_at DESC\nLIMIT 10;"
    }
   ]
  }
 ]
}