{
 "title": "Prometheus Metrics",
 "tags": [ "prometheus" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Portfolios Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(prometheus_metrics_service_portfolios_processed_total{command=\"rebalance_simple\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average rebalance time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_metrics_service_command_execution_duration_seconds_sum{command=\"rebalance_simple\"}[$__rate_interval]) / rate(prometheus_metrics_service_command_execution_duration_seconds_count{command=\"rebalance_simple\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Timeouts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(prometheus_metrics_service_command_timeouts_total{command=\"rebalance_simple\"}[$__rate_interval]) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}