name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Maintenance Mode
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/rebalax
            docker exec rebalax-app php artisan down || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "~/rebalax"

      - name: Run remote deployment script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: APP_KEY,APP_ENV,APP_URL,APP_DEBUG,DB_DATABASE,DB_USERNAME,DB_PASSWORD,REDIS_PASSWORD,QUEUE_CONNECTION,GRAFANA_ADMIN_USER,GRAFANA_ADMIN_PASSWORD
          script: |
            chmod +x ~/rebalax/deploy.sh
            ~/rebalax/deploy.sh
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_URL: ${{ secrets.APP_URL }}
          APP_DEBUG: ${{ secrets.APP_DEBUG }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          QUEUE_CONNECTION: ${{ secrets.QUEUE_CONNECTION }}
          GRAFANA_ADMIN_USER: ${{ secrets.GRAFANA_ADMIN_USER }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

      - name: Clean up old files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker system prune -f
            docker volume prune -f
            docker image prune -a -f
            rm -rf ~/rebalax/storage/logs/*.log

      - name: Clear Maintenance Mode
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/rebalax
            docker exec rebalax-app php artisan up
