name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "~/rebalax"

      - name: Run remote deployment script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: APP_KEY,APP_ENV,APP_URL,DB_DATABASE,DB_USERNAME,DB_PASSWORD,REDIS_PASSWORD,QUEUE_CONNECTION
          script: |
            chmod +x ~/rebalax/deploy.sh
            ~/rebalax/deploy.sh
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_ENV: ${{ secrets.APP_ENV }}
          APP_URL: ${{ secrets.APP_URL }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          QUEUE_CONNECTION: ${{ secrets.QUEUE_CONNECTION }}
